### ISSUE TITLE
it stops when defined inside a docker compose stack

### ISSUE THREAD

**Issue by cascandaliato** [cascandaliato/docker-restarter#2]
In qdm12/gluetun#641, @Blavkentropy1 said:
> I did find I had to put it outside of the stack. Your container would attempt to restart itself. But actually stop if it was inside the stack, and not restart the other container's. Possibly a issue from my side thought

**Comment by cascandaliato** [comment]
@Blavkentropy1, did you possibly add a `depends_on` to the restarter itself? Could you share the container logs (`docker logs restarter`) if you happen to replicate the problem?

**Comment by Blavkentropy1** [comment]
Hi @cascandaliato 

Thanks for your time and container, I have attempted to replicate the original issue. Unfortunately I cant.. 
I'm happy to do any testing to replicate this though. 

I was one foot out the door when I hit the issue, and I moved restarter  outside the stack to test is when I got home. 

Below is my Stack that I had the issue in.  Happy to

I do recall seeing something along the lines of
" Restarting the following container(s) in 10 seconds because container gluetun (re)started: autobrr, flaresolverr, prowlarr, restarter" in the logs, and "restarter" container just stopping and not restarting the effected containers. 

My Setup
OS: Debian 12.1
Docker: 24.0.6
Built in Portainer Business 2.19.1 

`version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    restart: "unless-stopped"
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    environment:
      - EXTRA_SUBNETS=192.168.0.0/24
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_PRESHARED_KEY=
      - WIREGUARD_ADDRESSES=
      - TZ=Australia/melbourne
    ports:
      - 8000:8000     #Http Control
      - 9696:9696     #Prowlarr
      - 7474:7474     #Autobrr
      - 8191:8191     #Flaresolver
	  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    restart: "unless-stopped"
    network_mode: "service:gluetun"
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/melbourne
      - network:container:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - prowlarr:/config
      - /home/ryan/Dropbox/Program Backup/Arrr_Server/backup/Prowlarr_backup/:/Backup/

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: "unless-stopped"
    network_mode: "service:gluetun"
    container_name: flaresolverr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/melbourne
      - network:container:gluetun
      - LOG_LEVEL=info 
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
		
  restarter:
    image: ghcr.io/cascandaliato/docker-restarter  
    container_name: restarter
    restart: "unless-stopped"	
    environment:		
      - TZ=Australia/melbourne
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  prowlarr:
  autobrr:`

**Comment by cascandaliato** [comment]
Please try moving it back inside the docker compose yaml and let me know. I tried adding `restart: "unless-stopped"` to my services thinking it was going to interfere but I could not replicate the problem.

It will be useful to get the container logs. At start-up it should print the list of dependencies:
```
Container torrent depends on service vpn
...
```

**Comment by Blavkentropy1** [comment]
Hi @cascandaliato 

I have moved the config back inside the stack, and I cant replicate the issue now. 
I'm happy for this to be closed. If I do manage to get this again, I will re-open a ticket.
